cat("\n\n\n\n*****Creation of Matrix*****\n\n\n\n")
m<-matrix(c(1,2,3,4))
cat("\nOutput:")
print(m)
cat("\n\n\n\n Using nrow:")
m<-matrix(c(1,2,3,4,5,6), nrow = 2)
cat("\nOutput:")
print(m)
cat("\n\n\n\n Using byrow:")
m<-matrix(c(1,2,3,4,5,6),nrow=2,byrow = TRUE)
cat("\nOutput:")
print(m)
cat("\n\n\n\n Using Dimension names:")
rname<-c("row1","row2")
cname<-c("col1","col2","col3")
m<-matrix(c(1,2,3,4,5,6),nrow = 2,byrow = TRUE,dimnames = list(rname,cname))
cat("\nOutput:")
print(m)
cat("\n\n\n\n Using Structures:")
str(m)
cat("\nOutput:")
print(m)
cat("\n\n\n\n *****Accessing the Matrix*****")
cat("\n\n\n\n Accessing single row :")
cat("\nOutput:")
print(m[1,])
cat("\n\n\n\n Accessing one column  :")
cat("\nOutput:")
print(m[,1])
cat("\n\n\t\t*****Arithmetic Operation*****")
m1<-matrix(c(5,10,20,15,25,30),nrow=2)
cat("\n Matrix 1 : \n")
print(m1)
m2<-matrix(c(3,7,60,15,35,10),nrow=2)
cat("\n Matrix 2 :\n")
print(m2)
cat("\nAddition Of Matrices : \n")
m3=m1+m2
cat("\n")
print(m3)
cat("\nSubtraction Of Matrices : \n ")
m3=m1-m2
cat("\n")
print(m3)
cat("\n Basic multiplication Of Matrices : \n")
m3=m1*m2
cat("\n")
print(m3)
m4<-matrix(c(12,34,12,34,23,14),ncol=2)
cat("\n Matrix 3 : \n")
print(m4)
cat("\nMultiplication Of Matrices : \n")
m3=m1%*%m4
cat("\n")
print(m3)
cat("\n Basic multiplication Of Matrix with an element : \n")
m3=m1*15
cat("\n")
print(m3)
cat("\nDivision Of Matrices : \n ")
m3=m1/m2
cat("\n")
print(m3)
cat("\n\n\t\t*****Matrix Operations*****\n\n")
cat("\nTransformation Of Matrix 1 : \n")
print(t(m1))
cat("\nMerging Of Matrix 1 and Matrix 2 : \n")
cat("\n I cbind \n")
print(cbind(m1,m2))
cat("\n II rbind \n")
print(rbind(m1,m2))
cat("\nCrossproduct Of Matrix 1 and Matrix 2 : \n")
print(crossprod(m1,m2))
cat("\nDiagonal Of Matrix 1 : \n")
print(diag(m1))
print(diag(c(10,20,30,40)))

cat("\nInverse Of Matrix  : \n")
mat<-matrix(c(1,2,3,4),nrow=2)
print(mat)
cat("\n")
print(solve(mat))
cat("\nEign values and Eign Vectors   : \n")
print(eigen(mat))
cat("\n Values")
print(eigen(mat)$values)
cat("\n Vectors")
print(eigen(mat)$vector)
cat("\nRank Of Matrix  : \n")
print(qr(mat)$rank)
cat("\nRowMeans Of Matrix  : \n")
print(rowMeans(mat))
cat("\nColMeans Of Matrix  : \n")
print(colMeans(mat))
cat("\nColSums Of Matrix  : \n")
print(colSums(mat))

